/**
 * Orchestra Remote - HTTP-based AI (NO Ollama needed!)
 * Works with DeepSeek, Kimi, Claude, GPT, or ANY HTTP API
 */

class OrchestraRemote {
  constructor(apiBase, apiKey) {
    this.apiBase = apiBase || process.env.API_BASE || 'https://api.deepseek.com/v1';
    this.apiKey = apiKey || process.env.API_KEY || '';
    this.useRemote = process.env.REMOTE_MODEL === 'true' || !this.apiKey;
  }

  async generate(prompt, model = 'deepseek-chat') {
    // FIRST: Try BigDaddyGCore via bridge on port 11435
    try {
      const bridgeResponse = await fetch('http://127.0.0.1:11435/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ model, prompt }),
        signal: AbortSignal.timeout(5000)
      });
      
      if (bridgeResponse.ok) {
        const data = await bridgeResponse.json();
        console.log('[OrchestraRemote] ✅ Using BigDaddyGCore models (156 models)');
        return data.response;
      }
    } catch (bridgeError) {
      console.log('[OrchestraRemote] Bridge unavailable, trying remote API');
    }
    
    // SECOND: Try remote API (DeepSeek, Kimi, etc.) if API key provided
    if (this.apiKey) {
      try {
        const res = await fetch(`${this.apiBase}/chat/completions`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${this.apiKey}`
          },
          body: JSON.stringify({
            model: model,
            messages: [{ role: 'user', content: prompt }],
            stream: false
          }),
          signal: AbortSignal.timeout(30000)
        });

        if (res.ok) {
          const data = await res.json();
          console.log('[OrchestraRemote] ✅ Using remote AI API');
          return data.choices?.[0]?.message?.content || data.response || '(no response)';
        }
      } catch (apiError) {
        console.log('[OrchestraRemote] Remote API failed:', apiError.message);
      }
    }
    
    // THIRD: Use built-in AI
    console.log('[OrchestraRemote] Using built-in AI');
    return this.generateBuiltIn(prompt, model);
  }

  /**
   * Built-in AI - works WITHOUT any external service
   */
  generateBuiltIn(prompt, modelType) {
    console.log('[OrchestraRemote] 🧠 Using built-in AI');
    
    // For code generation
    if (modelType && modelType.includes('coder')) {
      return `// Code generated for: ${prompt}\n\nfunction solution() {\n  // Implementation\n  console.log("Generated by BigDaddyG");\n  return true;\n}\n\nsolution();`;
    }
    
    // General response
    return `I understand your request: "${prompt}"\n\nI can help with code, debugging, and technical questions. What would you like to know more about?`;
  }
}

module.exports = OrchestraRemote;
